apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-container
        image: deathranger/todo:latest
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: python-lb
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: python
  type: LoadBalancer        
